// Code generated by scripts/generate_iso3166.py; DO NOT EDIT.
export interface CountryOption { code: string; label: string; name_en: string; emoji: string }
export const ISO3166_COUNTRIES = [
  {
    "code": "us",
    "label": "美国",
    "name_en": "United States",
    "emoji": "🇺🇸"
  },
  {
    "code": "jp",
    "label": "日本",
    "name_en": "Japan",
    "emoji": "🇯🇵"
  },
  {
    "code": "hk",
    "label": "中国香港特别行政区",
    "name_en": "Hong Kong SAR China",
    "emoji": "🇭🇰"
  },
  {
    "code": "sg",
    "label": "新加坡",
    "name_en": "Singapore",
    "emoji": "🇸🇬"
  },
  {
    "code": "tw",
    "label": "台湾",
    "name_en": "Taiwan",
    "emoji": "🇹🇼"
  },
  {
    "code": "kr",
    "label": "韩国",
    "name_en": "South Korea",
    "emoji": "🇰🇷"
  },
  {
    "code": "in",
    "label": "印度",
    "name_en": "India",
    "emoji": "🇮🇳"
  },
  {
    "code": "ae",
    "label": "阿拉伯联合酋长国",
    "name_en": "United Arab Emirates",
    "emoji": "🇦🇪"
  },
  {
    "code": "ch",
    "label": "瑞士",
    "name_en": "Switzerland",
    "emoji": "🇨🇭"
  },
  {
    "code": "au",
    "label": "澳大利亚",
    "name_en": "Australia",
    "emoji": "🇦🇺"
  },
  {
    "code": "de",
    "label": "德国",
    "name_en": "Germany",
    "emoji": "🇩🇪"
  },
  {
    "code": "gb",
    "label": "英国",
    "name_en": "United Kingdom",
    "emoji": "🇬🇧"
  },
  {
    "code": "ca",
    "label": "加拿大",
    "name_en": "Canada",
    "emoji": "🇨🇦"
  },
  {
    "code": "fr",
    "label": "法国",
    "name_en": "France",
    "emoji": "🇫🇷"
  },
  {
    "code": "vn",
    "label": "越南",
    "name_en": "Vietnam",
    "emoji": "🇻🇳"
  },
  {
    "code": "ru",
    "label": "俄罗斯",
    "name_en": "Russia",
    "emoji": "🇷🇺"
  },
  {
    "code": "ua",
    "label": "乌克兰",
    "name_en": "Ukraine",
    "emoji": "🇺🇦"
  },
  {
    "code": "tr",
    "label": "土耳其",
    "name_en": "Turkey",
    "emoji": "🇹🇷"
  },
  {
    "code": "ng",
    "label": "尼日利亚",
    "name_en": "Nigeria",
    "emoji": "🇳🇬"
  },
  {
    "code": "ad",
    "label": "安道尔",
    "name_en": "Andorra",
    "emoji": "🇦🇩"
  },
  {
    "code": "af",
    "label": "阿富汗",
    "name_en": "Afghanistan",
    "emoji": "🇦🇫"
  },
  {
    "code": "ag",
    "label": "安提瓜和巴布达",
    "name_en": "Antigua & Barbuda",
    "emoji": "🇦🇬"
  },
  {
    "code": "ai",
    "label": "安圭拉",
    "name_en": "Anguilla",
    "emoji": "🇦🇮"
  },
  {
    "code": "al",
    "label": "阿尔巴尼亚",
    "name_en": "Albania",
    "emoji": "🇦🇱"
  },
  {
    "code": "am",
    "label": "亚美尼亚",
    "name_en": "Armenia",
    "emoji": "🇦🇲"
  },
  {
    "code": "ao",
    "label": "安哥拉",
    "name_en": "Angola",
    "emoji": "🇦🇴"
  },
  {
    "code": "aq",
    "label": "南极洲",
    "name_en": "Antarctica",
    "emoji": "🇦🇶"
  },
  {
    "code": "ar",
    "label": "阿根廷",
    "name_en": "Argentina",
    "emoji": "🇦🇷"
  },
  {
    "code": "as",
    "label": "美属萨摩亚",
    "name_en": "American Samoa",
    "emoji": "🇦🇸"
  },
  {
    "code": "at",
    "label": "奥地利",
    "name_en": "Austria",
    "emoji": "🇦🇹"
  },
  {
    "code": "aw",
    "label": "阿鲁巴",
    "name_en": "Aruba",
    "emoji": "🇦🇼"
  },
  {
    "code": "ax",
    "label": "奥兰群岛",
    "name_en": "Åland Islands",
    "emoji": "🇦🇽"
  },
  {
    "code": "az",
    "label": "阿塞拜疆",
    "name_en": "Azerbaijan",
    "emoji": "🇦🇿"
  },
  {
    "code": "ba",
    "label": "波斯尼亚和黑塞哥维那",
    "name_en": "Bosnia & Herzegovina",
    "emoji": "🇧🇦"
  },
  {
    "code": "bb",
    "label": "巴巴多斯",
    "name_en": "Barbados",
    "emoji": "🇧🇧"
  },
  {
    "code": "bd",
    "label": "孟加拉国",
    "name_en": "Bangladesh",
    "emoji": "🇧🇩"
  },
  {
    "code": "be",
    "label": "比利时",
    "name_en": "Belgium",
    "emoji": "🇧🇪"
  },
  {
    "code": "bf",
    "label": "布基纳法索",
    "name_en": "Burkina Faso",
    "emoji": "🇧🇫"
  },
  {
    "code": "bg",
    "label": "保加利亚",
    "name_en": "Bulgaria",
    "emoji": "🇧🇬"
  },
  {
    "code": "bh",
    "label": "巴林",
    "name_en": "Bahrain",
    "emoji": "🇧🇭"
  },
  {
    "code": "bi",
    "label": "布隆迪",
    "name_en": "Burundi",
    "emoji": "🇧🇮"
  },
  {
    "code": "bj",
    "label": "贝宁",
    "name_en": "Benin",
    "emoji": "🇧🇯"
  },
  {
    "code": "bl",
    "label": "圣巴泰勒米",
    "name_en": "St. Barthélemy",
    "emoji": "🇧🇱"
  },
  {
    "code": "bm",
    "label": "百慕大",
    "name_en": "Bermuda",
    "emoji": "🇧🇲"
  },
  {
    "code": "bn",
    "label": "文莱",
    "name_en": "Brunei",
    "emoji": "🇧🇳"
  },
  {
    "code": "bo",
    "label": "玻利维亚",
    "name_en": "Bolivia",
    "emoji": "🇧🇴"
  },
  {
    "code": "bq",
    "label": "荷属加勒比区",
    "name_en": "Caribbean Netherlands",
    "emoji": "🇧🇶"
  },
  {
    "code": "br",
    "label": "巴西",
    "name_en": "Brazil",
    "emoji": "🇧🇷"
  },
  {
    "code": "bs",
    "label": "巴哈马",
    "name_en": "Bahamas",
    "emoji": "🇧🇸"
  },
  {
    "code": "bt",
    "label": "不丹",
    "name_en": "Bhutan",
    "emoji": "🇧🇹"
  },
  {
    "code": "bv",
    "label": "布韦岛",
    "name_en": "Bouvet Island",
    "emoji": "🇧🇻"
  },
  {
    "code": "bw",
    "label": "博茨瓦纳",
    "name_en": "Botswana",
    "emoji": "🇧🇼"
  },
  {
    "code": "by",
    "label": "白俄罗斯",
    "name_en": "Belarus",
    "emoji": "🇧🇾"
  },
  {
    "code": "bz",
    "label": "伯利兹",
    "name_en": "Belize",
    "emoji": "🇧🇿"
  },
  {
    "code": "cc",
    "label": "科科斯（基林）群岛",
    "name_en": "Cocos (Keeling) Islands",
    "emoji": "🇨🇨"
  },
  {
    "code": "cd",
    "label": "刚果（金）",
    "name_en": "Congo - Kinshasa",
    "emoji": "🇨🇩"
  },
  {
    "code": "cf",
    "label": "中非共和国",
    "name_en": "Central African Republic",
    "emoji": "🇨🇫"
  },
  {
    "code": "cg",
    "label": "刚果（布）",
    "name_en": "Congo - Brazzaville",
    "emoji": "🇨🇬"
  },
  {
    "code": "ci",
    "label": "科特迪瓦",
    "name_en": "Côte d’Ivoire",
    "emoji": "🇨🇮"
  },
  {
    "code": "ck",
    "label": "库克群岛",
    "name_en": "Cook Islands",
    "emoji": "🇨🇰"
  },
  {
    "code": "cl",
    "label": "智利",
    "name_en": "Chile",
    "emoji": "🇨🇱"
  },
  {
    "code": "cm",
    "label": "喀麦隆",
    "name_en": "Cameroon",
    "emoji": "🇨🇲"
  },
  {
    "code": "cn",
    "label": "中国",
    "name_en": "China",
    "emoji": "🇨🇳"
  },
  {
    "code": "co",
    "label": "哥伦比亚",
    "name_en": "Colombia",
    "emoji": "🇨🇴"
  },
  {
    "code": "cr",
    "label": "哥斯达黎加",
    "name_en": "Costa Rica",
    "emoji": "🇨🇷"
  },
  {
    "code": "cu",
    "label": "古巴",
    "name_en": "Cuba",
    "emoji": "🇨🇺"
  },
  {
    "code": "cv",
    "label": "佛得角",
    "name_en": "Cape Verde",
    "emoji": "🇨🇻"
  },
  {
    "code": "cw",
    "label": "库拉索",
    "name_en": "Curaçao",
    "emoji": "🇨🇼"
  },
  {
    "code": "cx",
    "label": "圣诞岛",
    "name_en": "Christmas Island",
    "emoji": "🇨🇽"
  },
  {
    "code": "cy",
    "label": "塞浦路斯",
    "name_en": "Cyprus",
    "emoji": "🇨🇾"
  },
  {
    "code": "cz",
    "label": "捷克",
    "name_en": "Czechia",
    "emoji": "🇨🇿"
  },
  {
    "code": "dj",
    "label": "吉布提",
    "name_en": "Djibouti",
    "emoji": "🇩🇯"
  },
  {
    "code": "dk",
    "label": "丹麦",
    "name_en": "Denmark",
    "emoji": "🇩🇰"
  },
  {
    "code": "dm",
    "label": "多米尼克",
    "name_en": "Dominica",
    "emoji": "🇩🇲"
  },
  {
    "code": "do",
    "label": "多米尼加共和国",
    "name_en": "Dominican Republic",
    "emoji": "🇩🇴"
  },
  {
    "code": "dz",
    "label": "阿尔及利亚",
    "name_en": "Algeria",
    "emoji": "🇩🇿"
  },
  {
    "code": "ec",
    "label": "厄瓜多尔",
    "name_en": "Ecuador",
    "emoji": "🇪🇨"
  },
  {
    "code": "ee",
    "label": "爱沙尼亚",
    "name_en": "Estonia",
    "emoji": "🇪🇪"
  },
  {
    "code": "eg",
    "label": "埃及",
    "name_en": "Egypt",
    "emoji": "🇪🇬"
  },
  {
    "code": "eh",
    "label": "西撒哈拉",
    "name_en": "Western Sahara",
    "emoji": "🇪🇭"
  },
  {
    "code": "er",
    "label": "厄立特里亚",
    "name_en": "Eritrea",
    "emoji": "🇪🇷"
  },
  {
    "code": "es",
    "label": "西班牙",
    "name_en": "Spain",
    "emoji": "🇪🇸"
  },
  {
    "code": "et",
    "label": "埃塞俄比亚",
    "name_en": "Ethiopia",
    "emoji": "🇪🇹"
  },
  {
    "code": "fi",
    "label": "芬兰",
    "name_en": "Finland",
    "emoji": "🇫🇮"
  },
  {
    "code": "fj",
    "label": "斐济",
    "name_en": "Fiji",
    "emoji": "🇫🇯"
  },
  {
    "code": "fk",
    "label": "福克兰群岛",
    "name_en": "Falkland Islands",
    "emoji": "🇫🇰"
  },
  {
    "code": "fm",
    "label": "密克罗尼西亚",
    "name_en": "Micronesia",
    "emoji": "🇫🇲"
  },
  {
    "code": "fo",
    "label": "法罗群岛",
    "name_en": "Faroe Islands",
    "emoji": "🇫🇴"
  },
  {
    "code": "ga",
    "label": "加蓬",
    "name_en": "Gabon",
    "emoji": "🇬🇦"
  },
  {
    "code": "gd",
    "label": "格林纳达",
    "name_en": "Grenada",
    "emoji": "🇬🇩"
  },
  {
    "code": "ge",
    "label": "格鲁吉亚",
    "name_en": "Georgia",
    "emoji": "🇬🇪"
  },
  {
    "code": "gf",
    "label": "法属圭亚那",
    "name_en": "French Guiana",
    "emoji": "🇬🇫"
  },
  {
    "code": "gg",
    "label": "根西岛",
    "name_en": "Guernsey",
    "emoji": "🇬🇬"
  },
  {
    "code": "gh",
    "label": "加纳",
    "name_en": "Ghana",
    "emoji": "🇬🇭"
  },
  {
    "code": "gi",
    "label": "直布罗陀",
    "name_en": "Gibraltar",
    "emoji": "🇬🇮"
  },
  {
    "code": "gl",
    "label": "格陵兰",
    "name_en": "Greenland",
    "emoji": "🇬🇱"
  },
  {
    "code": "gm",
    "label": "冈比亚",
    "name_en": "Gambia",
    "emoji": "🇬🇲"
  },
  {
    "code": "gn",
    "label": "几内亚",
    "name_en": "Guinea",
    "emoji": "🇬🇳"
  },
  {
    "code": "gp",
    "label": "瓜德罗普",
    "name_en": "Guadeloupe",
    "emoji": "🇬🇵"
  },
  {
    "code": "gq",
    "label": "赤道几内亚",
    "name_en": "Equatorial Guinea",
    "emoji": "🇬🇶"
  },
  {
    "code": "gr",
    "label": "希腊",
    "name_en": "Greece",
    "emoji": "🇬🇷"
  },
  {
    "code": "gs",
    "label": "南乔治亚和南桑威奇群岛",
    "name_en": "South Georgia & South Sandwich Islands",
    "emoji": "🇬🇸"
  },
  {
    "code": "gt",
    "label": "危地马拉",
    "name_en": "Guatemala",
    "emoji": "🇬🇹"
  },
  {
    "code": "gu",
    "label": "关岛",
    "name_en": "Guam",
    "emoji": "🇬🇺"
  },
  {
    "code": "gw",
    "label": "几内亚比绍",
    "name_en": "Guinea-Bissau",
    "emoji": "🇬🇼"
  },
  {
    "code": "gy",
    "label": "圭亚那",
    "name_en": "Guyana",
    "emoji": "🇬🇾"
  },
  {
    "code": "hm",
    "label": "赫德岛和麦克唐纳群岛",
    "name_en": "Heard & McDonald Islands",
    "emoji": "🇭🇲"
  },
  {
    "code": "hn",
    "label": "洪都拉斯",
    "name_en": "Honduras",
    "emoji": "🇭🇳"
  },
  {
    "code": "hr",
    "label": "克罗地亚",
    "name_en": "Croatia",
    "emoji": "🇭🇷"
  },
  {
    "code": "ht",
    "label": "海地",
    "name_en": "Haiti",
    "emoji": "🇭🇹"
  },
  {
    "code": "hu",
    "label": "匈牙利",
    "name_en": "Hungary",
    "emoji": "🇭🇺"
  },
  {
    "code": "id",
    "label": "印度尼西亚",
    "name_en": "Indonesia",
    "emoji": "🇮🇩"
  },
  {
    "code": "ie",
    "label": "爱尔兰",
    "name_en": "Ireland",
    "emoji": "🇮🇪"
  },
  {
    "code": "il",
    "label": "以色列",
    "name_en": "Israel",
    "emoji": "🇮🇱"
  },
  {
    "code": "im",
    "label": "马恩岛",
    "name_en": "Isle of Man",
    "emoji": "🇮🇲"
  },
  {
    "code": "io",
    "label": "英属印度洋领地",
    "name_en": "British Indian Ocean Territory",
    "emoji": "🇮🇴"
  },
  {
    "code": "iq",
    "label": "伊拉克",
    "name_en": "Iraq",
    "emoji": "🇮🇶"
  },
  {
    "code": "ir",
    "label": "伊朗",
    "name_en": "Iran",
    "emoji": "🇮🇷"
  },
  {
    "code": "is",
    "label": "冰岛",
    "name_en": "Iceland",
    "emoji": "🇮🇸"
  },
  {
    "code": "it",
    "label": "意大利",
    "name_en": "Italy",
    "emoji": "🇮🇹"
  },
  {
    "code": "je",
    "label": "泽西岛",
    "name_en": "Jersey",
    "emoji": "🇯🇪"
  },
  {
    "code": "jm",
    "label": "牙买加",
    "name_en": "Jamaica",
    "emoji": "🇯🇲"
  },
  {
    "code": "jo",
    "label": "约旦",
    "name_en": "Jordan",
    "emoji": "🇯🇴"
  },
  {
    "code": "ke",
    "label": "肯尼亚",
    "name_en": "Kenya",
    "emoji": "🇰🇪"
  },
  {
    "code": "kg",
    "label": "吉尔吉斯斯坦",
    "name_en": "Kyrgyzstan",
    "emoji": "🇰🇬"
  },
  {
    "code": "kh",
    "label": "柬埔寨",
    "name_en": "Cambodia",
    "emoji": "🇰🇭"
  },
  {
    "code": "ki",
    "label": "基里巴斯",
    "name_en": "Kiribati",
    "emoji": "🇰🇮"
  },
  {
    "code": "km",
    "label": "科摩罗",
    "name_en": "Comoros",
    "emoji": "🇰🇲"
  },
  {
    "code": "kn",
    "label": "圣基茨和尼维斯",
    "name_en": "St. Kitts & Nevis",
    "emoji": "🇰🇳"
  },
  {
    "code": "kp",
    "label": "朝鲜",
    "name_en": "North Korea",
    "emoji": "🇰🇵"
  },
  {
    "code": "kw",
    "label": "科威特",
    "name_en": "Kuwait",
    "emoji": "🇰🇼"
  },
  {
    "code": "ky",
    "label": "开曼群岛",
    "name_en": "Cayman Islands",
    "emoji": "🇰🇾"
  },
  {
    "code": "kz",
    "label": "哈萨克斯坦",
    "name_en": "Kazakhstan",
    "emoji": "🇰🇿"
  },
  {
    "code": "la",
    "label": "老挝",
    "name_en": "Laos",
    "emoji": "🇱🇦"
  },
  {
    "code": "lb",
    "label": "黎巴嫩",
    "name_en": "Lebanon",
    "emoji": "🇱🇧"
  },
  {
    "code": "lc",
    "label": "圣卢西亚",
    "name_en": "St. Lucia",
    "emoji": "🇱🇨"
  },
  {
    "code": "li",
    "label": "列支敦士登",
    "name_en": "Liechtenstein",
    "emoji": "🇱🇮"
  },
  {
    "code": "lk",
    "label": "斯里兰卡",
    "name_en": "Sri Lanka",
    "emoji": "🇱🇰"
  },
  {
    "code": "lr",
    "label": "利比里亚",
    "name_en": "Liberia",
    "emoji": "🇱🇷"
  },
  {
    "code": "ls",
    "label": "莱索托",
    "name_en": "Lesotho",
    "emoji": "🇱🇸"
  },
  {
    "code": "lt",
    "label": "立陶宛",
    "name_en": "Lithuania",
    "emoji": "🇱🇹"
  },
  {
    "code": "lu",
    "label": "卢森堡",
    "name_en": "Luxembourg",
    "emoji": "🇱🇺"
  },
  {
    "code": "lv",
    "label": "拉脱维亚",
    "name_en": "Latvia",
    "emoji": "🇱🇻"
  },
  {
    "code": "ly",
    "label": "利比亚",
    "name_en": "Libya",
    "emoji": "🇱🇾"
  },
  {
    "code": "ma",
    "label": "摩洛哥",
    "name_en": "Morocco",
    "emoji": "🇲🇦"
  },
  {
    "code": "mc",
    "label": "摩纳哥",
    "name_en": "Monaco",
    "emoji": "🇲🇨"
  },
  {
    "code": "md",
    "label": "摩尔多瓦",
    "name_en": "Moldova",
    "emoji": "🇲🇩"
  },
  {
    "code": "me",
    "label": "黑山",
    "name_en": "Montenegro",
    "emoji": "🇲🇪"
  },
  {
    "code": "mf",
    "label": "法属圣马丁",
    "name_en": "St. Martin",
    "emoji": "🇲🇫"
  },
  {
    "code": "mg",
    "label": "马达加斯加",
    "name_en": "Madagascar",
    "emoji": "🇲🇬"
  },
  {
    "code": "mh",
    "label": "马绍尔群岛",
    "name_en": "Marshall Islands",
    "emoji": "🇲🇭"
  },
  {
    "code": "mk",
    "label": "北马其顿",
    "name_en": "North Macedonia",
    "emoji": "🇲🇰"
  },
  {
    "code": "ml",
    "label": "马里",
    "name_en": "Mali",
    "emoji": "🇲🇱"
  },
  {
    "code": "mm",
    "label": "缅甸",
    "name_en": "Myanmar (Burma)",
    "emoji": "🇲🇲"
  },
  {
    "code": "mn",
    "label": "蒙古",
    "name_en": "Mongolia",
    "emoji": "🇲🇳"
  },
  {
    "code": "mo",
    "label": "中国澳门特别行政区",
    "name_en": "Macao SAR China",
    "emoji": "🇲🇴"
  },
  {
    "code": "mp",
    "label": "北马里亚纳群岛",
    "name_en": "Northern Mariana Islands",
    "emoji": "🇲🇵"
  },
  {
    "code": "mq",
    "label": "马提尼克",
    "name_en": "Martinique",
    "emoji": "🇲🇶"
  },
  {
    "code": "mr",
    "label": "毛里塔尼亚",
    "name_en": "Mauritania",
    "emoji": "🇲🇷"
  },
  {
    "code": "ms",
    "label": "蒙特塞拉特",
    "name_en": "Montserrat",
    "emoji": "🇲🇸"
  },
  {
    "code": "mt",
    "label": "马耳他",
    "name_en": "Malta",
    "emoji": "🇲🇹"
  },
  {
    "code": "mu",
    "label": "毛里求斯",
    "name_en": "Mauritius",
    "emoji": "🇲🇺"
  },
  {
    "code": "mv",
    "label": "马尔代夫",
    "name_en": "Maldives",
    "emoji": "🇲🇻"
  },
  {
    "code": "mw",
    "label": "马拉维",
    "name_en": "Malawi",
    "emoji": "🇲🇼"
  },
  {
    "code": "mx",
    "label": "墨西哥",
    "name_en": "Mexico",
    "emoji": "🇲🇽"
  },
  {
    "code": "my",
    "label": "马来西亚",
    "name_en": "Malaysia",
    "emoji": "🇲🇾"
  },
  {
    "code": "mz",
    "label": "莫桑比克",
    "name_en": "Mozambique",
    "emoji": "🇲🇿"
  },
  {
    "code": "na",
    "label": "纳米比亚",
    "name_en": "Namibia",
    "emoji": "🇳🇦"
  },
  {
    "code": "nc",
    "label": "新喀里多尼亚",
    "name_en": "New Caledonia",
    "emoji": "🇳🇨"
  },
  {
    "code": "ne",
    "label": "尼日尔",
    "name_en": "Niger",
    "emoji": "🇳🇪"
  },
  {
    "code": "nf",
    "label": "诺福克岛",
    "name_en": "Norfolk Island",
    "emoji": "🇳🇫"
  },
  {
    "code": "ni",
    "label": "尼加拉瓜",
    "name_en": "Nicaragua",
    "emoji": "🇳🇮"
  },
  {
    "code": "nl",
    "label": "荷兰",
    "name_en": "Netherlands",
    "emoji": "🇳🇱"
  },
  {
    "code": "no",
    "label": "挪威",
    "name_en": "Norway",
    "emoji": "🇳🇴"
  },
  {
    "code": "np",
    "label": "尼泊尔",
    "name_en": "Nepal",
    "emoji": "🇳🇵"
  },
  {
    "code": "nr",
    "label": "瑙鲁",
    "name_en": "Nauru",
    "emoji": "🇳🇷"
  },
  {
    "code": "nu",
    "label": "纽埃",
    "name_en": "Niue",
    "emoji": "🇳🇺"
  },
  {
    "code": "nz",
    "label": "新西兰",
    "name_en": "New Zealand",
    "emoji": "🇳🇿"
  },
  {
    "code": "om",
    "label": "阿曼",
    "name_en": "Oman",
    "emoji": "🇴🇲"
  },
  {
    "code": "pa",
    "label": "巴拿马",
    "name_en": "Panama",
    "emoji": "🇵🇦"
  },
  {
    "code": "pe",
    "label": "秘鲁",
    "name_en": "Peru",
    "emoji": "🇵🇪"
  },
  {
    "code": "pf",
    "label": "法属波利尼西亚",
    "name_en": "French Polynesia",
    "emoji": "🇵🇫"
  },
  {
    "code": "pg",
    "label": "巴布亚新几内亚",
    "name_en": "Papua New Guinea",
    "emoji": "🇵🇬"
  },
  {
    "code": "ph",
    "label": "菲律宾",
    "name_en": "Philippines",
    "emoji": "🇵🇭"
  },
  {
    "code": "pk",
    "label": "巴基斯坦",
    "name_en": "Pakistan",
    "emoji": "🇵🇰"
  },
  {
    "code": "pl",
    "label": "波兰",
    "name_en": "Poland",
    "emoji": "🇵🇱"
  },
  {
    "code": "pm",
    "label": "圣皮埃尔和密克隆群岛",
    "name_en": "St. Pierre & Miquelon",
    "emoji": "🇵🇲"
  },
  {
    "code": "pn",
    "label": "皮特凯恩群岛",
    "name_en": "Pitcairn Islands",
    "emoji": "🇵🇳"
  },
  {
    "code": "pr",
    "label": "波多黎各",
    "name_en": "Puerto Rico",
    "emoji": "🇵🇷"
  },
  {
    "code": "ps",
    "label": "巴勒斯坦领土",
    "name_en": "Palestinian Territories",
    "emoji": "🇵🇸"
  },
  {
    "code": "pt",
    "label": "葡萄牙",
    "name_en": "Portugal",
    "emoji": "🇵🇹"
  },
  {
    "code": "pw",
    "label": "帕劳",
    "name_en": "Palau",
    "emoji": "🇵🇼"
  },
  {
    "code": "py",
    "label": "巴拉圭",
    "name_en": "Paraguay",
    "emoji": "🇵🇾"
  },
  {
    "code": "qa",
    "label": "卡塔尔",
    "name_en": "Qatar",
    "emoji": "🇶🇦"
  },
  {
    "code": "re",
    "label": "留尼汪",
    "name_en": "Réunion",
    "emoji": "🇷🇪"
  },
  {
    "code": "ro",
    "label": "罗马尼亚",
    "name_en": "Romania",
    "emoji": "🇷🇴"
  },
  {
    "code": "rs",
    "label": "塞尔维亚",
    "name_en": "Serbia",
    "emoji": "🇷🇸"
  },
  {
    "code": "rw",
    "label": "卢旺达",
    "name_en": "Rwanda",
    "emoji": "🇷🇼"
  },
  {
    "code": "sa",
    "label": "沙特阿拉伯",
    "name_en": "Saudi Arabia",
    "emoji": "🇸🇦"
  },
  {
    "code": "sb",
    "label": "所罗门群岛",
    "name_en": "Solomon Islands",
    "emoji": "🇸🇧"
  },
  {
    "code": "sc",
    "label": "塞舌尔",
    "name_en": "Seychelles",
    "emoji": "🇸🇨"
  },
  {
    "code": "sd",
    "label": "苏丹",
    "name_en": "Sudan",
    "emoji": "🇸🇩"
  },
  {
    "code": "se",
    "label": "瑞典",
    "name_en": "Sweden",
    "emoji": "🇸🇪"
  },
  {
    "code": "sh",
    "label": "圣赫勒拿",
    "name_en": "St. Helena",
    "emoji": "🇸🇭"
  },
  {
    "code": "si",
    "label": "斯洛文尼亚",
    "name_en": "Slovenia",
    "emoji": "🇸🇮"
  },
  {
    "code": "sj",
    "label": "斯瓦尔巴和扬马延",
    "name_en": "Svalbard & Jan Mayen",
    "emoji": "🇸🇯"
  },
  {
    "code": "sk",
    "label": "斯洛伐克",
    "name_en": "Slovakia",
    "emoji": "🇸🇰"
  },
  {
    "code": "sl",
    "label": "塞拉利昂",
    "name_en": "Sierra Leone",
    "emoji": "🇸🇱"
  },
  {
    "code": "sm",
    "label": "圣马力诺",
    "name_en": "San Marino",
    "emoji": "🇸🇲"
  },
  {
    "code": "sn",
    "label": "塞内加尔",
    "name_en": "Senegal",
    "emoji": "🇸🇳"
  },
  {
    "code": "so",
    "label": "索马里",
    "name_en": "Somalia",
    "emoji": "🇸🇴"
  },
  {
    "code": "sr",
    "label": "苏里南",
    "name_en": "Suriname",
    "emoji": "🇸🇷"
  },
  {
    "code": "ss",
    "label": "南苏丹",
    "name_en": "South Sudan",
    "emoji": "🇸🇸"
  },
  {
    "code": "st",
    "label": "圣多美和普林西比",
    "name_en": "São Tomé & Príncipe",
    "emoji": "🇸🇹"
  },
  {
    "code": "sv",
    "label": "萨尔瓦多",
    "name_en": "El Salvador",
    "emoji": "🇸🇻"
  },
  {
    "code": "sx",
    "label": "荷属圣马丁",
    "name_en": "Sint Maarten",
    "emoji": "🇸🇽"
  },
  {
    "code": "sy",
    "label": "叙利亚",
    "name_en": "Syria",
    "emoji": "🇸🇾"
  },
  {
    "code": "sz",
    "label": "斯威士兰",
    "name_en": "Eswatini",
    "emoji": "🇸🇿"
  },
  {
    "code": "tc",
    "label": "特克斯和凯科斯群岛",
    "name_en": "Turks & Caicos Islands",
    "emoji": "🇹🇨"
  },
  {
    "code": "td",
    "label": "乍得",
    "name_en": "Chad",
    "emoji": "🇹🇩"
  },
  {
    "code": "tf",
    "label": "法属南部领地",
    "name_en": "French Southern Territories",
    "emoji": "🇹🇫"
  },
  {
    "code": "tg",
    "label": "多哥",
    "name_en": "Togo",
    "emoji": "🇹🇬"
  },
  {
    "code": "th",
    "label": "泰国",
    "name_en": "Thailand",
    "emoji": "🇹🇭"
  },
  {
    "code": "tj",
    "label": "塔吉克斯坦",
    "name_en": "Tajikistan",
    "emoji": "🇹🇯"
  },
  {
    "code": "tk",
    "label": "托克劳",
    "name_en": "Tokelau",
    "emoji": "🇹🇰"
  },
  {
    "code": "tl",
    "label": "东帝汶",
    "name_en": "Timor-Leste",
    "emoji": "🇹🇱"
  },
  {
    "code": "tm",
    "label": "土库曼斯坦",
    "name_en": "Turkmenistan",
    "emoji": "🇹🇲"
  },
  {
    "code": "tn",
    "label": "突尼斯",
    "name_en": "Tunisia",
    "emoji": "🇹🇳"
  },
  {
    "code": "to",
    "label": "汤加",
    "name_en": "Tonga",
    "emoji": "🇹🇴"
  },
  {
    "code": "tt",
    "label": "特立尼达和多巴哥",
    "name_en": "Trinidad & Tobago",
    "emoji": "🇹🇹"
  },
  {
    "code": "tv",
    "label": "图瓦卢",
    "name_en": "Tuvalu",
    "emoji": "🇹🇻"
  },
  {
    "code": "tz",
    "label": "坦桑尼亚",
    "name_en": "Tanzania",
    "emoji": "🇹🇿"
  },
  {
    "code": "ug",
    "label": "乌干达",
    "name_en": "Uganda",
    "emoji": "🇺🇬"
  },
  {
    "code": "um",
    "label": "美国本土外小岛屿",
    "name_en": "U.S. Outlying Islands",
    "emoji": "🇺🇲"
  },
  {
    "code": "uy",
    "label": "乌拉圭",
    "name_en": "Uruguay",
    "emoji": "🇺🇾"
  },
  {
    "code": "uz",
    "label": "乌兹别克斯坦",
    "name_en": "Uzbekistan",
    "emoji": "🇺🇿"
  },
  {
    "code": "va",
    "label": "梵蒂冈",
    "name_en": "Vatican City",
    "emoji": "🇻🇦"
  },
  {
    "code": "vc",
    "label": "圣文森特和格林纳丁斯",
    "name_en": "St. Vincent & Grenadines",
    "emoji": "🇻🇨"
  },
  {
    "code": "ve",
    "label": "委内瑞拉",
    "name_en": "Venezuela",
    "emoji": "🇻🇪"
  },
  {
    "code": "vg",
    "label": "英属维尔京群岛",
    "name_en": "British Virgin Islands",
    "emoji": "🇻🇬"
  },
  {
    "code": "vi",
    "label": "美属维尔京群岛",
    "name_en": "U.S. Virgin Islands",
    "emoji": "🇻🇮"
  },
  {
    "code": "vu",
    "label": "瓦努阿图",
    "name_en": "Vanuatu",
    "emoji": "🇻🇺"
  },
  {
    "code": "wf",
    "label": "瓦利斯和富图纳",
    "name_en": "Wallis & Futuna",
    "emoji": "🇼🇫"
  },
  {
    "code": "ws",
    "label": "萨摩亚",
    "name_en": "Samoa",
    "emoji": "🇼🇸"
  },
  {
    "code": "ye",
    "label": "也门",
    "name_en": "Yemen",
    "emoji": "🇾🇪"
  },
  {
    "code": "yt",
    "label": "马约特",
    "name_en": "Mayotte",
    "emoji": "🇾🇹"
  },
  {
    "code": "za",
    "label": "南非",
    "name_en": "South Africa",
    "emoji": "🇿🇦"
  },
  {
    "code": "zm",
    "label": "赞比亚",
    "name_en": "Zambia",
    "emoji": "🇿🇲"
  },
  {
    "code": "zw",
    "label": "津巴布韦",
    "name_en": "Zimbabwe",
    "emoji": "🇿🇼"
  }
] as const satisfies readonly CountryOption[]
export const ISO3166_COUNTRY_BY_CODE: Record<string, CountryOption> = Object.fromEntries(ISO3166_COUNTRIES.map(item => [item.code, item]))
