#!/usr/bin/env python3
"""Generate ISO-3166 alpha-2 country/region tables for Go and TypeScript.

Source JSON files are downloaded into data/iso3166 from umpirsky/country-list:
- data/iso3166/country_zh_CN.json
- data/iso3166/country_en.json
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ZH_PATH = ROOT / "data" / "iso3166" / "country_zh_CN.json"
EN_PATH = ROOT / "data" / "iso3166" / "country_en.json"
GO_PATH = ROOT / "internal" / "geoip" / "iso3166_data.go"
TS_PATH = ROOT / "web" / "src" / "data" / "iso3166.ts"

POPULAR = ["US", "JP", "HK", "SG", "TW", "KR", "IN", "AE", "CH", "AU", "DE", "GB", "CA", "FR", "VN", "RU", "UA", "TR", "NG"]
SPECIAL_EN_ALIASES = {"GB": ["UK", "Great Britain"], "US": ["USA"]}
SPECIAL_ZH_ALIASES = {"HK": ["香港"], "MO": ["澳门"], "US": ["美國"], "GB": ["英國"]}


def esc_go(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def flag_emoji(alpha2: str) -> str:
    if len(alpha2) != 2 or not alpha2.isalpha():
        return "🌍"
    return "".join(chr(0x1F1E6 + ord(ch) - ord("A")) for ch in alpha2.upper())


def ordered_codes(codes: set[str]) -> list[str]:
    out = [c for c in POPULAR if c in codes]
    out.extend(c for c in sorted(codes) if c not in set(out))
    return out


def main() -> None:
    zh = json.loads(ZH_PATH.read_text(encoding="utf-8"))
    en = json.loads(EN_PATH.read_text(encoding="utf-8"))
    codes = {c.upper() for c in zh} & {c.upper() for c in en}
    rows = [(code, zh[code], en[code], flag_emoji(code)) for code in ordered_codes(codes)]

    go_lines = [
        "// Code generated by scripts/generate_iso3166.py; DO NOT EDIT.",
        "package geoip",
        "",
        "type CountryInfo struct {",
        "\tCode string",
        "\tNameZH string",
        "\tNameEN string",
        "\tEmoji string",
        "\tAliases []string",
        "}",
        "",
        "var iso3166Countries = []CountryInfo{",
    ]
    for code, name_zh, name_en, emoji in rows:
        aliases = []
        aliases.extend(SPECIAL_ZH_ALIASES.get(code, []))
        aliases.extend(SPECIAL_EN_ALIASES.get(code, []))
        alias_text = "nil"
        if aliases:
            alias_text = "[]string{" + ", ".join(esc_go(a) for a in aliases) + "}"
        go_lines.append(f"\t{{Code: {esc_go(code.lower())}, NameZH: {esc_go(name_zh)}, NameEN: {esc_go(name_en)}, Emoji: {esc_go(emoji)}, Aliases: {alias_text}}},")
    go_lines.extend([
        "}",
        "",
        "var iso3166CountryByCode = func() map[string]CountryInfo {",
        "\tout := make(map[string]CountryInfo, len(iso3166Countries))",
        "\tfor _, item := range iso3166Countries {",
        "\t\tout[item.Code] = item",
        "\t}",
        "\treturn out",
        "}()",
        "",
    ])
    GO_PATH.write_text("\n".join(go_lines), encoding="utf-8")

    TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    ts_rows = [
        {"code": code.lower(), "label": name_zh, "name_en": name_en, "emoji": emoji}
        for code, name_zh, name_en, emoji in rows
    ]
    ts = (
        "// Code generated by scripts/generate_iso3166.py; DO NOT EDIT.\n"
        "export interface CountryOption { code: string; label: string; name_en: string; emoji: string }\n"
        f"export const ISO3166_COUNTRIES = {json.dumps(ts_rows, ensure_ascii=False, indent=2)} as const satisfies readonly CountryOption[]\n"
        "export const ISO3166_COUNTRY_BY_CODE: Record<string, CountryOption> = Object.fromEntries(ISO3166_COUNTRIES.map(item => [item.code, item]))\n"
    )
    TS_PATH.write_text(ts, encoding="utf-8")
    print(f"generated {len(rows)} ISO countries")
    print(GO_PATH)
    print(TS_PATH)


if __name__ == "__main__":
    main()
